# Generated by Django 4.2.7 on 2025-12-22 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('api_key', models.CharField(help_text='API key for brand authentication', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='licenses.brand')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['brand', 'name'],
                'unique_together': {('brand', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('customer_email', models.EmailField(db_index=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_keys', to='licenses.brand')),
            ],
            options={
                'db_table': 'license_keys',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='valid', max_length=20)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('max_seats', models.IntegerField(blank=True, help_text='Maximum number of activations allowed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='licenses.licensekey')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='licenses.product')),
            ],
            options={
                'db_table': 'licenses',
            },
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance_id', models.CharField(help_text='Site URL, host, machine ID, etc.', max_length=255)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='licenses.license')),
            ],
            options={
                'db_table': 'activations',
            },
        ),
        migrations.AddIndex(
            model_name='licensekey',
            index=models.Index(fields=['key'], name='license_key_key_8fecb2_idx'),
        ),
        migrations.AddIndex(
            model_name='licensekey',
            index=models.Index(fields=['customer_email'], name='license_key_custome_dc5384_idx'),
        ),
        migrations.AddIndex(
            model_name='licensekey',
            index=models.Index(fields=['brand', 'customer_email'], name='license_key_brand_i_466ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['license_key', 'status'], name='licenses_license_5a9496_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['product', 'status'], name='licenses_product_4f46b6_idx'),
        ),
        migrations.AddIndex(
            model_name='activation',
            index=models.Index(fields=['license', 'is_active'], name='activations_license_5b9a24_idx'),
        ),
        migrations.AddIndex(
            model_name='activation',
            index=models.Index(fields=['instance_id'], name='activations_instanc_93a23c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activation',
            unique_together={('license', 'instance_id', 'is_active')},
        ),
    ]
